
# ====================== below code is just for template ===============================

from typing import TypedDict, Annotated
from langgraph.graph import add_messages

class AgentState(TypedDict):
    messages: Annotated[list, add_messages]
    iteration: int
    plan: str  # step-by-step plan generated by the planner node
    start_time: float  # wall-clock start time (time.time()) for timeout detection

